title:            "Hiroshi Fukada"
description:      "Hiroshi in Jekyll"
logo:             bulb.png
disqus_shortname: hiroshi
# Assign a default image for your site's header and footer
default_bg:       bg.jpg
search:           false
share:            false
# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         false
# Turn on or off the fin animations in the header and footer
animated_fins:	  false
# Specify the fin color in RGB value
fin_color:        "255,255,255"
# Change url to your domain. Leave localhost server or blank when working locally.
url:              http://fukada.us/

# Owner/author information
owner:
  name:           Hiroshi Fukada
  avatar:         profile.png
  email:          hiroshi@fukada.us
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Hiroshi Fukada is a Computer Engineer and Software Developer. His interests are anything related to software and showing the world what he&#8217;s made.
  # Social networking links used in footer. Update and remove as you like.
  # To register at HMFAYSAL SOCIAL, visit http://social.hmfaysal.tk
  twitter:        
  facebook:       
  github:         hfukada
  stackexchange:  
  linkedin:       http://www.linkedin.com/pub/hiroshi-fukada/65/340/bab/
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/+HiroshiFukada/posts

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
#  - title: <i class="icon-book"></i> Documentation
#    url: /documentation
#  - title: Categories
#    url: /categories
#  - title: Tags
#    url: /tags
#  - title: Faysal who?
#    url: /hossain-mohd-faysal

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
pygments:    true
markdown:    kramdown
paginate:    6
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
